name: pawsome
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  widgets:
    path: module/widgets
  gen:
    path: module/gen


  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  auto_route: ^7.8.4
  vexana: ^3.5.4
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  fonts:
    - family: Galano-Grotesque
      fonts:
        - asset: asset/fonts/Galano-Grotesque/GalanoGrotesqueMedium.otf
        - asset: asset/fonts/Galano-Grotesque/GalanoGrotesqueSemiBold.otf

  assets:
    - asset/translation/